services:
  - type: web
    name: carrec-api-dikko
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: >
      gunicorn src.main:app
      -k uvicorn.workers.UvicornWorker
      --workers ${UVICORN_WORKERS:-1}
      --timeout 120
      --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        value: sqlite:////tmp/app.db
      - key: UVICORN_WORKERS
        value: "1"
      - key: PYTHON_VERSION
        value: "3.11"
